# Generated by Django 5.0.2 on 2024-02-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.IntegerField(),
        ),
    ]
